### ISSUE TITLE
It's not working now?

### ISSUE THREAD

**Issue by blackstrip** [mindcollapse/SoftEtherPy#10]
I change the hashlib.new('sha') to hashlib.new('sha1'), but the api_authenticate is still not work.

**Comment by rahul260792** [comment]
Any update on this?

**Comment by 59adc5ed-4a64-4984-bf6a-2b9117da6625** [comment]
@rahul260792 what exactly is the problem/error?

**Comment by ford1813** [comment]
api_authenticate is still not work ?
