### ISSUE TITLE
Source materials

### ISSUE THREAD

**Issue by jpillora** [mindcollapse/SoftEtherPy#6]
I've been looking the management API spec and it looks like this library implements it, though it would be nice to see the API documentation. Does documentation exist? or did you just read the C source?

**Comment by volodymyrsmirnov** [comment]
@jpillora no public documentation exists. You can see this file for the list of RPC calls and their parameters https://github.com/SoftEtherVPN/SoftEtherVPN/blob/17e624ac26bb95e111790313512b986f189c37f5/src/Cedar/Admin.c#L443

**Comment by jpillora** [comment]
Ah great, thanks!
